version: "3"
services: # nơi build image và tạo container
  api-gateway:
    container_name: api-gateway
    build: ./api-getway # docker build . -t ...
    # image: undertarke/nodeadv02 # build bằng hub docker
    ports:
      - 8080:8080
    networks:
      - baemin
  notify-service:
    container_name: notify-service
    build: ./notify-service
    networks:
      - baemin

  order-service:
    container_name: order-service
    build: ./order-service
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - DATABASE_URL=mongodb://root:password123@mongodb-primary:27017/
    networks:
      - baemin

  food-service:
    container_name: food-service
    build: ./food-service
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - DATABASE_URL=mongodb://root:password123@mongodb-primary:27017/
    networks:
      - baemin
    ports:
      - "8080:8080"

  mongodb-primary:
    image: docker.io/bitnami/mongodb:8.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - "mongodb_master_data:/bitnami/mongodb"
    ports:
      - "27017:27017"
    networks:
      - baemin

  product-service:
    container_name: product-service
    build: ./product-service
    environment:
      #   - DATABASE_URL=postgresql://postgres:1234@some-postgres:5432/db_amazon
      - REDIS_HOST=some-redis
      - REDIS_PORT=6379
    networks:
      - baemin

  shipping-service:
    container_name: shipping-service
    build: ./shipping-service
    networks:
      - baemin

  user-service:
    container_name: user-service
    build: ./user-service
    networks:
      - baemin

  cart-service:
    container_name: cart-service
    build: ./cart-service
    networks:
      - baemin

  auth-service:
    container_name: auth-service
    build: ./auth-service
    networks:
      - baemin

networks:
  baemin:
    external: true # sử dụng mạng có sẵn trước đó

# docker-compose up -d
